//
// Created by  Oussama Siyagh on 09/02/2020.
//

#ifndef UNTITLED1_GESTIONNAIRE_DES_ERREURS_H
#define UNTITLED1_GESTIONNAIRE_DES_ERREURS_H

#define NOMBRES_DES_ERREURS	24

#include "main.h"

typedef enum _error_codes {
    AFFECTATION_SYMBOL_EXPECTED_ERROR, //0
    ASSIGNEMENT_OR_FUNCTION_CALL_END_STATEMENT_ERROR,//1
    CLOSE_CURLY_BRACKET_TOKEN_ERROR,//2
    OPEN_CURLY_BRACKET_TOKEN_ERROR,//3
    CONDITION_ERROR,//4
    NUMERIC_TERM_EXPECTED_ERROR,//5
    NUMBER_EXPECTED_ERROR,//6
    NUMBER_ID_EXPECTED_ERROR,//7
    IDENTIFIER_EXPECTED_ERROR,//8
    OPEN_PARENTHESIS_TOKEN_ERROR,//9
    CLOSE_PARENTHESIS_TOKEN_ERROR,//10
    IN_EXPECTED_ERROR,//11
    IF_BODY_ERROR,//12
    ELSE_STATEMENT_BODY,//13
    LOOP_BODY_ERROR,//14
    FUNCTION_BODY_ERROR,//15
    FACT_ERROR,//16
    TERM_ERROR,
    NO_ARGUMENT_PRINT_ERROR,//17
    //semantic errors:
    EXPECTED_NUMBER_TYPE,
    FUNCTION_CALL_ERROR,
    NO_VALUE_ERROR,
    ARGUMENT_NUMBER_ERROR,//21
    BREAK_ERROR,
} code_erreur;


void afficherErreur(code_erreur);

#endif //UNTITLED1_GESTIONNAIRE_DES_ERREURS_H
